export const LOAD_AND_GROUP_DATASET = 'LOAD_AND_GROUP_DATASET';
export const GET_ALL_DATASETS = 'GET_ALL_DATASETS';
export const GET_ALL_DISTANCES = 'GET_ALL_DISTANCES';
export const UPDATE_OPERATOR = 'UPDATE_OPERATOR';
export const GET_ALL_DATASET_QUERIES = 'GET_ALL_DATASET_QUERIES';
export const SELECT_QUERY = 'SELECT_QUERY';